export enum ROUTE {
  LANDING_PAGE = "/home",
  LOGIN = "/login",
  ABOUT = "/about",
  REGISTER = "/register",
  DASHBOARD = "/dashboard",
  LEARN_MORE = "/learn-more",
  USER_SETTINGS = "/user-settings",
  CREATE_LESSON = "/create-lesson",
  EDIT_LESSON = "/edit-lesson/:lessonId",
  FORGOT_PASSWORD = "/forgot-password",
  RESET_PASSWORD = "/reset-password",
  PAGE404 = "/error",
  PRIVACY_POLICY = "/privacy-policy",
  SUPPORT = "/support",
  FLASHCARDS_BROWSE = "/flashcards/:lessonId/browse",
  FLASHCARDS_REVIEW = "/flashcards/:lessonId/review",
  ABOUT_US = "/about-us",
}
